spring.profiles.active: development

---

spring:
  config:
    activate:
      on-profile: development

spring.aop.proxy-target-class: false
spring.http.log-request-details: true
logging.level.web: debug

custom.webflux:
  enabled: true
  initMessage: hello2

---

spring:
  config:
    activate:
      on-profile: production

spring.aop.proxy-target-class: true
spring.http.log-request-details: false
logging.level.web: debug
