spring:
  profiles:
    active: development

hotire.webflux:
  enabled: true
  initMessage: hello2



---
spring.profiles: development

spring.aop.proxy-target-class: false
spring.http.log-request-details: true
logging.level.web: debug




---

spring.profiles: production


spring.aop.proxy-target-class: true
spring.http.log-request-details: false
logging.level.web: debug
